---    
  - name: Check if Homebrew is installed
    command: brew --version
    register: brew_installed
    changed_when: false

  - name: Install Homebrew if not installed
    command: >
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    when: brew_installed.rc != 0
