---
- name: Update and install packages on Fedora server
  hosts: 192.168.0.2X
  become: true
  
  tasks:
    - name: Update system
      dnf:
        name: '*'
        state: latest
    
    - name: Install packages
      dnf:
        name:
          - plexmediaserver
          - syncthing
          - docker
          - qbittorrent
        state: latest
    
    - name: Download & install Lazydocker
      shell: |
      wget https://github.com/jesseduffield/lazydocker/releases/download/v0.20.0/lazydocker_0.20.0_Linux_x86_64.tar.gz  
      tar zxf lazydocker_

      