---
- name: Check if Oh My Zsh directory exists
  stat:
    path: ~/.oh-my-zsh
  register: ohmyzsh_stat
  changed_when: false

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/ohmyzsh_install.sh
  when: ohmyzsh_stat.stat.exists == false

- name: Install Oh My Zsh if not installed
  command: >
    /bin/bash /tmp/ohmyzsh_install.sh
  when: ohmyzsh_stat.stat.exists == false

- name: Change the user's shell to Zsh
  command: chsh -s /bin/zsh {{ lookup('pipe', 'whoami') }}
  when: ohmyzsh_stat.stat.exists == false

- name: Source the .zshrc file
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  when: ohmyzsh_stat.stat.exists == false
