---
- name: Ensure the Docker group exists
  group:
    name: docker
    state: present

- name: Add castro to the Docker group
  user:
    name: castro
    groups: docker  # Add the user to the Docker group
    append: yes  # This appends the user to the group without removing them from other groups
    
- name: Download LazyDocker
  get_url:
    url: https://github.com/jesseduffield/lazydocker/releases/download/v0.21.1/lazydocker_0.21.1_Linux_x86.tar.gz
    dest: /home/castro/lazydocker_0.21.1_Linux_arm64.tar.gz

- name: Extract LazyDocker
  ansible.builtin.unarchive:
    src: /home/castro/lazydocker_0.21.1_Linux_arm64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Set execute permissions
  file:
    path: /usr/local/bin/lazydocker
    mode: '0755'

- name: Verify LazyDocker installation
  command: lazydocker --version
  register: lazydocker_version

