---
- name: Install LazyDocker
  command: curl -s https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

- name: Download LazyDocker
  get_url:
    url: https://github.com/jesseduffield/lazydocker/releases/download/v0.21.1/lazydocker_0.21.1_Linux_arm64.tar.gz
    dest: /tmp/lazydocker_0.21.1_Linux_arm64.tar.gz

- name: Extract LazyDocker
  ansible.builtin.unarchive:
    src: /tmp/lazydocker_0.21.1_Linux_arm64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    become: yes

- name: Set execute permissions
  file:
    path: /usr/local/bin/lazydocker
    mode: '0755'

- name: Verify LazyDocker installation
  command: lazydocker --version
  register: lazydocker_version

- name: Executing docker compose files 
  command:  

