---
- name: Clone the .dotfiles git repository
  git:
    repo: https://github.com/43hershel/.dotfiles
    dest: /Users/castro/
    update: yes

- name: Cloning oh-my-zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /Users/castro/.oh-my-zsh/plugins

- name: Cloning zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: /Users/castro/.oh-my-zsh/plugins

- name: Stowing the .zshrc file
  command: stow zsh -t /Users/castro

- name: Stowing the .gitconfig file
  command: stow git -t /Users/castro