---
- name: Clone the .dotfiles git repository
  git:
    repo: https://github.com/43hershel/.dotfiles
    dest: "{{ ansible_env.HOME }}/.dotfiles"

- name: Cloning oh-my-zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /Users/castro/.oh-my-zsh/plugins/zsh-autosuggestions

- name: Cloning zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: /Users/castro/.oh-my-zsh/plugins/zsh-syntax-highlighting

- name: Stowing the .zshrc file
  command: stow git -d ~/.dotfiles -t /Users/castro

- name: Stowing the .gitconfig file
  command: stow git -d ~/.dotfiles -t /Users/castro
