---
- name: Install and update packages on Fedora Server
  hosts: master
  become: true

  tasks:
    - name: Update packages
      dnf:
        name: "*"
        state: latest

    - #name: Adding Repositories
    #shell: | 
        #sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm;
        
    - name: Install packages
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - docker
        - docker-compose 
        - kitty 
        - htop
        - zsh
        - neofetch
        - git
        - samba
        - python3
        - pip

    - name: Enabling services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: 
        - docker 

    - name: Installing lazydocker
      shell: | 
        wget https://github.com/jesseduffield/lazydocker/releases/download/v0.20.0/lazydocker_0.20.0_Linux_x86_64.tar.gz;  
        tar zxf lazydocker_0.20.0_Linux_x86_64.tar.gz;
        sudo install lazydocker /usr/local/bin;
