---
- name: Install Homebrew on macOS
  hosts: macs
  tasks:
    - name: Check if Homebrew is installed
      command: /usr/local/bin/brew --version
      register: brew_check
      ignore_errors: yes

    - name: Install Homebrew if not installed
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      when: brew_check.rc != 0

    - name: Update Homebrew
      command: /usr/local/bin/brew update
      when: brew_check.rc == 0
