---
- name: Adding Tailscale repo 
  command: sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo

- name: Install required packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - htop
    - docker
    - docker-compose
    - git
    - neovim
    - tailscale
    - golang

- name: Create Documents directory
  file:
    path: "/home/castro/Documents"  # Use the HOME environment variable to get the current user's home directory
    state: directory
    mode: 0755

- name: Create Downloads directory
  file:
    path: "/home/castro/Downloads"  # Use the HOME environment variable to get the current user's home directory
    state: directory
    mode: 0755

- name: Create notes directory
  file:
    path: "/home/castro/notes"  # Use the HOME environment variable to get the current user's home directory
    state: directory
    mode: 0755
