---
- name: macOS "maverick" set-up playbook
  hosts: localhost 
  gather_facts: no
  ignore_errors: yes

  roles: 
#    - homebrew
#    - terminal
#    - packages
#    - app_store
#    - fonts
#    - torrent
#    - geerlingguy.mac.dock



  


