---
- name: macOS "maverick" set-up playbook
  hosts: localhost 
  gather_facts: no
  ignore_errors: yes

  roles: 
    - homebrew
    - packages
    - app_store
    - terminal
    - fonts
#    - torrent
    - geerlingguy.mac.dock



  


