---
- name: Start and enable SSH service
  service:
    name: sshd
    state: started
    enabled: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Start and enable Tailscale service
  systemd:
    name: tailscaled
    state: started
    enabled: yes
    