version: '3.8'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/bagheera/Grimorium:/config
      - /mnt/bagheera/Grimorium/Películas:/movies
      - /mnt/bagheera/Grimorium/Series:/tv
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/castro/.config:/config
      - /mnt/bagheera/_all:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  syncthing:
      image: syncthing/syncthing
      container_name: syncthing
      hostname: bagira
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - /home/castro/notes:/var/syncthing
      ports:
        - 8384:8384 # Web UI
        - 22000:22000/tcp # TCP file transfers
        - 22000:22000/udp # QUIC file transfers
        - 21027:21027/udp # Receive local discovery broadcasts
      restart: unless-stopped
  
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: 'host'
    volumes:
      - /mnt/bagheera/docker:/config
      - /mnt/bagheera/docker:/cache
      - /mnt/bagheera/Grimorium:/media
    restart: 'unless-stopped'
    extra_hosts:
      - "host.docker.internal:host-gateway"     
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
