--- 
- name: Adding fonts to homebrew
  command: brew install --cask font-jetbrains-mono-nerd-font

- name: Checking if JetBrains Mono is installed on macOS
  command: ls ~/Library/Fonts/JetBrainsMono[wght].ttf
  register: font_check

- name: Installing JetBrains Mono using Homebrew Cask
  command: brew install --cask font-jetbrains-mono
  when: font_check.rc != 0



