---
- name: Bagira restore playbook
  hosts: my_vm
  become: yes  # Run tasks with sudo
  ignore_errors: yes

  roles: 
    - update
    - packages
    - services 
    - docker
    - docker-compose






